preview: Check AUR first, improve help

diff --git a/fzur-info b/fzur-info
--- a/fzur-info
+++ b/fzur-info
@@ -8,48 +8,40 @@ bold=$(tput bold)
 red=$(tput setaf 1)
 reset=$(tput sgr0)
 
-if [ $# -ne 1 ]; then
-    echo "Usage: $0 package-name" && exit 1
-fi
+aur() {
+    if [ "$(find "$1.json" -mtime -1 2>/dev/null)" ]; then
+        info=$(cat "$1.json")
+    else
+        # Download the package info and flatten the arrays into comma separeated strings
+        info=$(curl -s "https://aur.archlinux.org/rpc/v5/info?arg=$1" |
+            jq -c '.["results"][0] | (.. | arrays) |= join("  ")')
 
-pacman -Si --color=always "$1" 2>/dev/null && exit
-
-mkdir -p "$dir"
-cd "$dir"
-
-if [ "$(find "$1.json" -mtime -1 2>/dev/null)" ]; then
-    info=$(cat "$1.json")
-else
-    # Download the package info and flatten the arrays into comma separeated strings
-    info=$(curl -s "https://aur.archlinux.org/rpc/v5/info?arg=$1" \
-        | jq -c '.["results"][0] | (.. | arrays) |= join("  ")')
-
-    if [ "$info" = null ]; then
-        echo "${red}Failed to fetch package information for $1.$reset"
-        exit 1
+        if [ "$info" = null ]; then
+            echo "${red}Failed to fetch package information for $1.$reset"
+            exit 1
+        fi
+        echo "$info" >"$1.json"
     fi
-    echo "$info" > "$1.json"
-fi
 
-get() {
-    local val
-    val=$(jq --arg key "$1" -r '.[$key]' <<< "$info")
-    [ "$val" = null ] && val=None
-    echo "$val"
-}
+    get() {
+        local val
+        val=$(jq --arg key "$1" -r '.[$key]' <<<"$info")
+        [ "$val" = null ] && val=None
+        echo "$val"
+    }
 
-maintainer=$(get Maintainer)
-[ "$maintainer" = None ] && maintainer=${red}Orphan${reset}
+    maintainer=$(get Maintainer)
+    [ "$maintainer" = None ] && maintainer=${red}Orphan${reset}
 
-version_label=$(get Version)
-outdated_timestamp=$(get OutOfDate)
-if [ "$outdated_timestamp" != None ]; then
-    version_label+=" ${red}Out-of-date ($(date -d @"${outdated_timestamp}" +%F))$reset"
-fi
+    version_label=$(get Version)
+    outdated_timestamp=$(get OutOfDate)
+    if [ "$outdated_timestamp" != None ]; then
+        version_label+=" ${red}Out-of-date ($(date -d @"${outdated_timestamp}" +%F))$reset"
+    fi
 
-# https://stackoverflow.com/a/58893261
-# TODO: Wrap words instead of characters
-cat <<EOF | column -t -s '|' --table-columns C1,C2 --table-noheadings --table-wrap C2
+    # https://stackoverflow.com/a/58893261
+    # TODO: Wrap words instead of characters
+    cat <<EOF | column -t -s '|' --table-columns C1,C2 --table-noheadings --table-wrap C2
 ${bold}Repository${reset}|: AUR
 ${bold}Package Base${reset}|: $(get PackageBase)
 ${bold}Version${reset}|: $version_label
@@ -68,3 +60,18 @@ ${bold}Popularity${reset}|: $(get Popularity)
 ${bold}First Submitted${reset}|: $(date -d @"$(get FirstSubmitted)")
 ${bold}Last Modified${reset}|: $(date -d @"$(get LastModified)")
 EOF
+}
+
+if [[ $# != 1 || $1 == -* ]]; then
+    echo 'Prints AUR or repository package information'
+    echo "Usage: $0 package-name" && exit 1
+fi
+
+mkdir -p "$dir"
+cd "$dir"
+
+if [ "$(grep "^$1$" ../packages.txt)" ]; then
+    aur "$1"
+else
+    pacman -Si --color=always "$1"
+fi
